name: gisaid

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  gisaid_EpiCoV_downloader-test:
    name: EpiCoV_downloader test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          path: EpiCoV_downloader

      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: EpiCoV_downloader/environment.yml
          activate-environment: gisaid
          python-version: ${{ matrix.python-version }}

      - name: use default firefox
        run: |
          conda uninstall firefox
          conda list
          which firefox

      - name: Check version
        run: |
          EpiCoV_downloader/gisaid_EpiCoV_downloader.py --version

      - name: Check downloading nextfasta and nextmeta
        run: |
          EpiCoV_downloader/gisaid_EpiCoV_downloader.py -u ${{ secrets.USER }} -p ${{ secrets.PASS }}

      - name: Cat log
        if: ${{ failure() }}
        run: |
          cat geckodriver.log
